### ISSUE TITLE
Running ANARCI (hmmer) in parallel for multiple sequences

### ISSUE THREAD

**Issue by y1zhou** [prihoda/AbNumber#13]
When we want to number multiple sequences, `ANARCI` [takes an `ncpu` argument](https://github.com/oxpig/ANARCI/blob/c2fd0f75ee3aa4cff842548d3d75b64815a8f663/lib/python/anarci/anarci.py#L857-L882) that allows running `hmmer` in parallel.   [Here](https://github.com/prihoda/AbNumber/blob/b8d8d655eca6440d4b1bd8559f4a49ccfa408cf7/abnumber/common.py#L23-L31) it seems the `Chain` class can only take one sequence and send it to `ANARCI`. Would it be possible to have a wrapper class (e.g. `Chains`) that runs `ANARCI` in parallel?

Great work with this package! Interpreting the outputs of these is so much easier than those of ANARCI's.

**Comment by prihoda** [comment]
Hi @y1zhou sorry for the late response, there has been an update - I released abnumber `0.3.3` which supports `Chain.batch(seq_dict, ...)` to process multiple input seqs at once. 

By default, abnumber uses `ncpu=None` because it calls `anarci()` not `run_anarci()`:
https://github.com/oxpig/ANARCI/blob/master/lib/python/anarci/anarci.py#L766-L767

So `Chain.batch` should now use multiprocessing as long as hmmer supports it - I haven't tested this extensively, might depend on your installation
